controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint1_controller:
      type: position_controllers/JointGroupPositionController

    joint2_controller:
      type: position_controllers/JointGroupPositionController

joint1_controller:
  ros__parameters:
    joints:
    - joint1
    - joint2
    interface_name: position